// src/lib/components/layout/Footer.svelte
<footer class="container mt-10">
    <div class="my-4 border-t-[3px] border-primary/50 pt-10">
        <h3 class="text-2xl leading-relaxed md:text-3xl">Get in touch:</h3>
        <div class="grid-cols-3 justify-between gap-10 md:grid">
            <div>
                <div class="text-lg leading-relaxed">
                    Astute Spruce, LLC
                    <br />
                    Brendan C. Ward
                    <br />
                    Owner | Lead software engineer
                    <br />
                    Email:{' '}
                    <a href="mailto:bcward@astutespruce.com">bcward@astutespruce.com</a>
                    <br />
                    Phone: 541-250-9544
                    <br />
                    Oregon, USA
                    <br />
                </div>
            </div>

            <div
                class="mt-4 border-t pt-4 text-lg leading-relaxed md:mt-0 md:mt-0 md:border-l md:border-t-0 md:pl-4 md:pt-0"
            >
                <a href="/about">About</a>
                <br />
                <a href="/services">Services</a>
                <br />
                <a href="/projects">Projects</a>
            </div>
            <div
                class="mt-4 border-t pt-4 text-lg leading-relaxed md:mt-0 md:mt-0 md:border-l md:border-t-0 md:pl-4 md:pt-0"
            >
                <a href="https://github.com/astutespruce">GitHub - Astute Spruce</a>
                <br />
                <a href="https://github.com/brendan-ward">GitHub - Brendan Ward</a>
                <br />
                <a href="https://www.linkedin.com/in/brendan-c-ward/"> LinkedIn</a>
            </div>
        </div>
    </div>
</footer>

// src/components/Layout/Footer.jsx
import React from 'react'

import { Container } from 'components/Grid'
import styled, { themeGet } from 'util/style'

const Wrapper = styled(Container)`
  margin-top: 2rem;
  border-top: 3px solid ${themeGet('colors.primary.300')};
  padding: 2rem 1rem;
  h3 {
    /* color: ${themeGet('colors.grey.300')}; */
    margin-bottom: 0.25em;
  }
`

const Footer = () => (
  <Wrapper as="footer">
    <h3>Get in touch:</h3>
    <p>
      Brendan C. Ward
      <br />
      Owner | Lead software engineer
      <br />
      Email:{' '}
      <a href="mailto:bcward@astutespruce.com">bcward@astutespruce.com</a>
      <br />
      Phone: 541-250-9544
      <br />
      Oregon, USA
      <br />
    </p>
  </Wrapper>
)

export default Footer
